import { LanguageCourse } from "./types";

export const hindiCourse: LanguageCourse = {
  slug: "hindi",
  name: "Hindi",
  flag: "🇮🇳",
  categories: [
    {
      id: "vowels",
      title: "Vowels (स्वर)",
      items: [
        { id: "v1", native: "अ", roman: "a", english: "a (as in 'about')" },
        { id: "v2", native: "आ", roman: "aa", english: "aa (as in 'father')" },
        { id: "v3", native: "इ", roman: "i", english: "i (as in 'bit')" },
        { id: "v4", native: "ई", roman: "ee", english: "ee (as in 'feet')" },
        { id: "v5", native: "उ", roman: "u", english: "u (as in 'put')" },
        { id: "v6", native: "ऊ", roman: "oo", english: "oo (as in 'boot')" },
        { id: "v7", native: "ऋ", roman: "ri", english: "ri (as in 'rig')" },
        { id: "v8", native: "ए", roman: "e", english: "e (as in 'bed')" },
        { id: "v9", native: "ऐ", roman: "ai", english: "ai (as in 'aisle')" },
        { id: "v10", native: "ओ", roman: "o", english: "o (as in 'go')" },
        { id: "v11", native: "औ", roman: "au", english: "au (as in 'cause')" },
        { id: "v12", native: "अं", roman: "am", english: "am (nasal sound)" },
        { id: "v13", native: "अः", roman: "ah", english: "ah (breathy sound)" },
      ],
    },
    {
      id: "consonants",
      title: "Consonants (व्यंजन)",
      items: [
        { id: "c1", native: "क", roman: "ka", english: "ka" },
        { id: "c2", native: "ख", roman: "kha", english: "kha" },
        { id: "c3", native: "ग", roman: "ga", english: "ga" },
        { id: "c4", native: "घ", roman: "gha", english: "gha" },
        { id: "c5", native: "ङ", roman: "nga", english: "nga" },
        { id: "c6", native: "च", roman: "cha", english: "cha" },
        { id: "c7", native: "छ", roman: "chha", english: "chha" },
        { id: "c8", native: "ज", roman: "ja", english: "ja" },
        { id: "c9", native: "झ", roman: "jha", english: "jha" },
        { id: "c10", native: "ञ", roman: "nya", english: "nya" },
        { id: "c11", native: "ट", roman: "ta", english: "ta (hard)" },
        { id: "c12", native: "ठ", roman: "tha", english: "tha (hard)" },
        { id: "c13", native: "ड", roman: "da", english: "da (hard)" },
        { id: "c14", native: "ढ", roman: "dha", english: "dha (hard)" },
        { id: "c15", native: "ण", roman: "na", english: "na (hard)" },
        { id: "c16", native: "त", roman: "ta", english: "ta (soft)" },
        { id: "c17", native: "थ", roman: "tha", english: "tha (soft)" },
        { id: "c18", native: "द", roman: "da", english: "da (soft)" },
        { id: "c19", native: "ध", roman: "dha", english: "dha (soft)" },
        { id: "c20", native: "न", roman: "na", english: "na (soft)" },
        { id: "c21", native: "प", roman: "pa", english: "pa" },
        { id: "c22", native: "फ", roman: "pha", english: "pha" },
        { id: "c23", native: "ब", roman: "ba", english: "ba" },
        { id: "c24", native: "भ", roman: "bha", english: "bha" },
        { id: "c25", native: "म", roman: "ma", english: "ma" },
      ],
    },
    {
      id: "more-consonants",
      title: "More Letters",
      items: [
        { id: "m1", native: "य", roman: "ya", english: "ya" },
        { id: "m2", native: "र", roman: "ra", english: "ra" },
        { id: "m3", native: "ल", roman: "la", english: "la" },
        { id: "m4", native: "व", roman: "va", english: "va" },
        { id: "m5", native: "श", roman: "sha", english: "sha" },
        { id: "m6", native: "ष", roman: "sha", english: "sha (retroflex)" },
        { id: "m7", native: "स", roman: "sa", english: "sa" },
        { id: "m8", native: "ह", roman: "ha", english: "ha" },
      ],
    },
    {
      id: "greetings",
      title: "Greetings",
      items: [
        { id: "g1", native: "नमस्ते", roman: "namaste", english: "Hello / Goodbye" },
        { id: "g2", native: "धन्यवाद", roman: "dhanyavaad", english: "Thank you" },
        { id: "g3", native: "कृपया", roman: "kripaya", english: "Please" },
        { id: "g4", native: "माफ़ कीजिए", roman: "maaf kijiye", english: "Sorry / Excuse me" },
        { id: "g5", native: "हाँ", roman: "haan", english: "Yes" },
        { id: "g6", native: "नहीं", roman: "nahin", english: "No" },
        { id: "g7", native: "अलविदा", roman: "alvida", english: "Goodbye (formal)" },
        { id: "g8", native: "शुभ रात्रि", roman: "shubh raatri", english: "Good night" },
      ],
    },
    {
      id: "phrases",
      title: "Everyday Phrases",
      items: [
        { id: "p1", native: "आप कैसे हैं?", roman: "aap kaise hain?", english: "How are you?" },
        { id: "p2", native: "मेरा नाम ... है", roman: "mera naam ... hai", english: "My name is ..." },
        { id: "p3", native: "आपका नाम क्या है?", roman: "aapka naam kya hai?", english: "What is your name?" },
        { id: "p4", native: "मुझे हिंदी नहीं आती", roman: "mujhe hindi nahin aati", english: "I don't know Hindi" },
        { id: "p5", native: "कृपया धीरे बोलिए", roman: "kripaya dheere boliye", english: "Please speak slowly" },
        { id: "p6", native: "यह क्या है?", roman: "yah kya hai?", english: "What is this?" },
        { id: "p7", native: "कितना पैसा?", roman: "kitna paisa?", english: "How much money?" },
        { id: "p8", native: "पानी", roman: "paani", english: "Water" },
        { id: "p9", native: "खाना", roman: "khaana", english: "Food" },
        { id: "p10", native: "मदद", roman: "madad", english: "Help" },
      ],
    },
  ],
};